# Generated by Django 6.0.5 on 2026-08-20 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0016_order_cost_price_at_sale_order_profit_at_sale'),
        ('products', '0016_product_allows_preorder_product_preorder_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_fee_at_order', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('queue_position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('cancel_reminder_sent', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preorder_source', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preorders', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preorders', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preorders', to='products.productvariant')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['product', 'status', 'created_at'], name='preorders_p_product_2c5d4b_idx'), models.Index(fields=['user', '-created_at'], name='preorders_p_user_id_4c66cc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'product', 'variant'), name='unique_pending_preorder_per_variant')],
            },
        ),
    ]
