# Generated by Django 6.0.5 on 2026-08-20 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_cost_price_at_sale_order_profit_at_sale'),
        ('preorders', '0001_initial'),
        ('products', '0016_product_allows_preorder_product_preorder_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='preorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('variant__isnull', True)), fields=('user', 'product'), name='unique_pending_preorder_no_variant'),
        ),
    ]
