# Generated by Django 6.0.5 on 2026-05-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_cannedresponse_remove_message_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='msg_type',
            field=models.CharField(choices=[('text', 'Text'), ('order_card', 'Order Card'), ('credentials_card', 'Credentials Card'), ('status_update', 'Status Update')], default='text', max_length=20),
        ),
    ]
