# Generated by Django 6.0.5 on 2026-07-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_metadata_message_msg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_email_alert_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
