# Generated by Django 6.0.5 on 2026-06-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_required_fields_has_variants_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='points_purchasable',
            field=models.BooleanField(default=False),
        ),
    ]
