# Generated by Django 6.0.5 on 2026-06-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_points_purchasable_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
    ]
