# Generated by Django 6.0.5 on 2026-06-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_add_points_earned_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='platform',
            field=models.CharField(blank=True, choices=[('steam', 'Steam'), ('epic', 'Epic Games'), ('gog', 'GOG'), ('xbox', 'Xbox'), ('psn', 'PlayStation'), ('battlenet', 'Battle.net'), ('ubisoft', 'Ubisoft Connect'), ('ea', 'EA App'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
