# Generated by Django 6.0.5 on 2026-06-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_orders_orde_user_id_0ae59f_idx'),
        ('products', '0009_add_platform_to_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='code',
            index=models.Index(fields=['product', 'status'], name='products_co_product_b707b6_idx'),
        ),
    ]
