# Generated by Django 6.0.5 on 2026-07-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_cost_price_productvariant_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='platform',
            field=models.CharField(blank=True, choices=[('steam', 'Steam'), ('epic', 'Epic Games'), ('gog', 'GOG'), ('xbox', 'Xbox'), ('psn', 'PlayStation'), ('battlenet', 'Battle.net'), ('ubisoft', 'Ubisoft Connect'), ('ea', 'EA App'), ('riot', 'Riot'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
