# Generated by Django 6.0.5 on 2026-08-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_code_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allows_preorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='preorder_note',
            field=models.TextField(blank=True),
        ),
    ]
