# Generated by Django 6.0.5 on 2026-05-30 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargerequest',
            name='reference',
            field=models.CharField(blank=True, help_text='Transaction ID from D17/BaridiMob', max_length=100),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_recharges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rechargerequest',
            name='method',
            field=models.CharField(choices=[('d17', 'D17'), ('baridimob', 'BaridiMob'), ('dahabia', 'Dahabia / E-DINAR'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('paypal', 'PayPal / Wise')], max_length=15),
        ),
        migrations.AlterField(
            model_name='rechargerequest',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
    ]
