# Generated by Django 6.0.5 on 2026-05-31 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rechargerequest_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('label', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'ordering': ['key'],
            },
        ),
        migrations.AlterField(
            model_name='rechargerequest',
            name='method',
            field=models.CharField(choices=[('d17', 'D17'), ('baridimob', 'BaridiMob'), ('dahabia', 'Dahabia / E-DINAR'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('ooredoo', 'Ooredoo'), ('orange', 'Orange Tunisia'), ('tunisie_telecom', 'Tunisie Telecom'), ('crypto', 'Cryptocurrency')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rechargerequest',
            name='reference',
            field=models.CharField(blank=True, help_text='Transaction ID / reference number', max_length=100),
        ),
        migrations.CreateModel(
            name='CryptoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USDT_TRC20', 'USDT TRC20'), ('USDT_ERC20', 'USDT ERC20'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('BNB', 'BNB BSC')], max_length=20)),
                ('wallet_address', models.CharField(max_length=200)),
                ('amount_crypto', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount_dt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('tx_hash', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirming', 'Confirming'), ('confirmed', 'Confirmed'), ('expired', 'Expired')], default='pending', max_length=15)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recharge_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_payment', to='payments.rechargerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
