# Generated by Django 6.0.5 on 2026-06-24 09:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_sitesettings_alter_rechargerequest_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rechargerequest',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='rechargerequest',
            name='reference',
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='amount_sent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount the client sent via D17', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='0.11 for ticket methods, 0 for D17', max_digits=5),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='ticket_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Face value of the physical/digital ticket', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='wallet_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Final DT amount credited to wallet after tax', max_digits=10),
        ),
        migrations.AlterField(
            model_name='rechargerequest',
            name='method',
            field=models.CharField(choices=[('ooredoo_ticket', 'Ooredoo Ticket'), ('orange_ticket', 'Orange Ticket'), ('d17_number', 'D17 - Phone Number'), ('d17_address', 'D17 - Address/RIB'), ('d17', 'D17 (legacy)'), ('baridimob', 'BaridiMob'), ('dahabia', 'Dahabia / E-DINAR'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('tunisie_telecom', 'Tunisie Telecom'), ('crypto', 'Cryptocurrency')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rechargerequest',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='recharge_proofs/'),
        ),
    ]
