# Generated by Django 6.0.5 on 2026-06-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_seed_sitesettings_payment_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptopayment',
            name='currency',
            field=models.CharField(choices=[('BINANCE', 'Binance')], max_length=20),
        ),
    ]
