# Generated by Django 6.0.5 on 2026-06-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_giftcardbatch_linked_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptopayment',
            name='currency',
            field=models.CharField(choices=[('BINANCE', 'Binance (USDT)'), ('BNB', 'BNB')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rechargerequest',
            name='method',
            field=models.CharField(choices=[('ooredoo_ticket', 'Ooredoo Ticket'), ('orange_ticket', 'Orange Ticket'), ('d17_number', 'D17 - Phone Number'), ('d17_address', 'D17 - Address/RIB'), ('bank_transfer', 'Bank Transfer (Bancaire)'), ('edinar', 'E-Dinar'), ('flouci', 'Flouci'), ('d17', 'D17 (legacy)'), ('baridimob', 'BaridiMob'), ('dahabia', 'Dahabia / E-DINAR'), ('bank', 'Bank Transfer (legacy)'), ('cash', 'Cash'), ('tunisie_telecom', 'Tunisie Telecom'), ('crypto', 'Cryptocurrency')], max_length=20),
        ),
    ]
