# Generated by Django 6.0.5 on 2026-07-07 12:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_add_bnb_remove_edinar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeTicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_items', to='payments.rechargerequest')),
            ],
        ),
    ]
