# Generated by Django 6.0.5 on 2026-07-24 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_complete', 'Order Complete'), ('recharge_approved', 'Recharge Approved'), ('recharge_rejected', 'Recharge Rejected'), ('ticket_reply', 'Ticket Reply'), ('referral_bonus', 'Referral Bonus'), ('flash_sale', 'Flash Sale'), ('wishlist_price_drop', 'Wishlist Price Drop')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
