# Generated by Django 6.0.5 on 2026-08-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_fix_product_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_complete', 'Order Complete'), ('recharge_approved', 'Recharge Approved'), ('recharge_rejected', 'Recharge Rejected'), ('ticket_reply', 'Ticket Reply'), ('referral_bonus', 'Referral Bonus'), ('flash_sale', 'Flash Sale'), ('wishlist_price_drop', 'Wishlist Price Drop'), ('preorder_placed', 'Pre-order Placed'), ('preorder_ready', 'Pre-order Ready'), ('preorder_reminder', 'Pre-order Cancel Window'), ('preorder_failed', 'Pre-order Failed')], max_length=30),
        ),
    ]
