# Generated by Django 6.0.5 on 2026-08-22 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, default='/', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_complete', 'Order Complete'), ('recharge_approved', 'Recharge Approved'), ('recharge_rejected', 'Recharge Rejected'), ('ticket_reply', 'Ticket Reply'), ('referral_bonus', 'Referral Bonus'), ('tier_upgrade', 'VIP Tier Upgrade'), ('flash_sale', 'Flash Sale'), ('preorder_fulfilled', 'Pre-order Fulfilled'), ('preorder_failed', 'Pre-order Failed'), ('announcement', 'Announcement'), ('wishlist_price_drop', 'Wishlist Price Drop'), ('preorder_placed', 'Pre-order Placed'), ('preorder_reminder', 'Pre-order Cancel Window')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'),
        ),
    ]
