# Generated by Django 6.0.5 on 2026-07-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_language_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orders_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
