# Generated by Django 6.0.5 on 2026-07-24 14:35

from django.db import migrations, models


def set_existing_verified(apps, schema_editor):
    """
    Everyone who already has an account predates this feature - grandfather
    them in as verified so nothing about their access changes. Only accounts
    created from here on start out with is_email_verified=False.
    """
    User = apps.get_model('users', 'User')
    User.objects.all().update(
        is_email_verified=True,
        email_verify_token=None,
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_orders_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_resend_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verify_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verify_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_existing_verified, noop),
    ]
