# Generated by Django 6.0.5 on 2026-05-31 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_promocode_order_bundle_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requires_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='service_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=15),
        ),
        migrations.CreateModel(
            name='OrderCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_encrypted', models.TextField()),
                ('is_used', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_log', models.JSONField(default=list)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'order credentials',
            },
        ),
    ]
