# Generated by Django 6.0.5 on 2026-06-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_requires_account_order_service_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='escrow_held',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordercredentials',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordercredentials',
            name='revealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_credentials', 'Pending Credentials'), ('paid_escrow', 'Paid — In Escrow'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('closed', 'Closed'), ('pending', 'Pending (legacy)'), ('cancelled', 'Cancelled')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='ordercredentials',
            name='data_encrypted',
            field=models.TextField(blank=True),
        ),
    ]
