# Generated by Django 6.0.5 on 2026-07-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_orders_orde_user_id_0ae59f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
