# Generated by Django 6.0.5 on 2026-07-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_promocode_one_per_user_promocodeusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost_price_at_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='profit_at_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
